//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 test.rc 使用
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_TEST232CAN_DIALOG           102
#define IDR_MAINFRAME                   128
#define IDD_TEST_DIALOG                 129
#define IDR_MENU1                       130
#define IDD_INFO_DIALOG                 131
#define IDD_TAB_CAR_DIALOG              133
#define IDD_TAB_DRIVER_DIALOG           134
#define IDD_TAB_POSITION_DIALOG         135
#define IDD_TAB_EXTREMUM_DIALOG         136
#define IDD_TAB_BATTERY_VOLTAGE_DIALOG  137
#define IDD_TAB_BATTERY_T_DIALOG        138
#define IDD_TAB_WARN_DIALOG             139
#define IDD_HAIDE_PROTOCOL_DIALOG       141
#define IDD_FRAME_RULE_DIALOG           143
#define IDC_COMBO_PORT                  1001
#define IDC_COMBO_INDEX                 1001
#define IDC_COMBO_BAUD                  1002
#define IDC_COMBO_CANIND                1002
#define IDC_BUTTON_CONNECT              1003
#define IDC_BUTTON_VERSION              1004
#define IDC_COMBO_DEV_TYPE              1004
#define IDC_BUTTON_BOARDSTATUS          1005
#define IDC_BUTTON_CANINFO              1006
#define IDC_BUTTON_STARTCAN             1007
#define IDC_BUTTON_RESETCAN             1008
#define IDC_BUTTON_EXITSYS              1009
#define IDC_BUTTON_CANSTATUS            1010
#define IDC_CHECK1                      1010
#define IDC_BUTTON_CANREGISTER          1011
#define IDC_BUTTON_PARSE                1011
#define IDC_CHECK2                      1011
#define IDC_BUTTON_BOARDSER             1012
#define IDC_CHECK_PARSE                 1012
#define IDC_BUTTON_BOARDTYPE            1013
#define IDC_EDIT_PARSE                  1013
#define IDC_BUTTON_SETTIME              1014
#define IDC_EDIT_VIN                    1014
#define IDC_BUTTON_FMVERSION            1015
#define IDC_EDIT_ICCID                  1015
#define IDC_COMBO_CANBAUD               1016
#define IDC_EDIT_ENCRYPTION             1016
#define IDC_BUTTON_CHGCANBAUD           1017
#define IDC_EDIT_SUBSYSTEM_NUM          1017
#define IDC_COMBO_232BAUD               1018
#define IDC_EDIT_LOGIN_ID               1018
#define IDC_BUTTON_CHG232BAUD           1019
#define IDC_EDIT_LOGOUT_ID              1019
#define IDC_EDIT_FILTERPARAMETER        1020
#define IDC_EDIT_WARN_LEVEL             1020
#define IDC_BUTTON_SETFILTER            1021
#define IDC_EDIT_WARN_FLAG              1021
#define IDC_EDIT_WRITEREGISTER          1022
#define IDC_TAB_MONITOR                 1022
#define IDC_BUTTON_WRITEREGISTER        1023
#define IDC_EDIT_H_V_BATTERY_SUBSYS_ID  1023
#define IDC_EDIT_SENDFRAMEID            1024
#define IDC_EDIT_STATUS                 1024
#define IDC_BUTTON_SEND                 1025
#define IDC_EDIT_LONGITUDE              1025
#define IDC_COMBO_SENDTYPE              1026
#define IDC_EDIT_H_V_BATTERY_ID         1026
#define IDC_COMBO_SENDFRAMETYPE         1027
#define IDC_EDIT_L_V_BATTERY_ID         1027
#define IDC_COMBO_SENDFRAMEFORMAT       1028
#define IDC_EDIT_BATTERY_V_H            1028
#define IDC_EDIT_SENDDATA               1029
#define IDC_EDIT_BATTERY_V_L            1029
#define IDC_EDIT_RESENDTIMES            1030
#define IDC_EDIT_H_T_BATTERY_SUBSYS_ID  1030
#define IDC_EDIT_SENDDELAYTIME          1031
#define IDC_EDIT_L_T_BATTERY_SUBSYS_ID  1031
#define IDC_EDIT_READREGISTER           1032
#define IDC_EDIT_H_T_BATTERY_ID         1032
#define IDC_EDIT_L_T_BATTERY_ID         1033
#define IDC_EDIT_BATTERY_T_H            1034
#define IDC_EDIT_BATTERY_T_L            1035
#define IDC_EDIT_LATITUDE               1036
#define IDC_EDIT_READGROUP              1037
#define IDC_EDIT1_DCDC_STATUS           1037
#define IDC_EDIT_REGISTERVAL            1038
#define IDC_EDIT_CAR_STATUS             1038
#define IDC_LIST_INFO                   1039
#define IDC_EDIT_CHARGING_STATUS        1039
#define IDC_EDIT_DRIVER_STATUS          1040
#define IDC_EDIT_BRAKING_STATUS         1041
#define IDC_EDIT_RUN_MODE               1042
#define IDC_EDIT_SPEED                  1043
#define IDC_EDIT_RESISTANCE             1044
#define IDC_EDIT_MIL                    1045
#define IDC_EDIT_GEARS                  1046
#define IDC_EDIT_SOC                    1047
#define IDC_EDIT1_TOTAL_V               1048
#define IDC_EDIT1_TOTAL_I               1049
#define IDC_EDIT_JOURNEY_SPEEDUP        1050
#define IDC_EDIT1_JOURNEY_BRAKE         1051
#define IDC_EDIT_MACHINE_NUM            1052
#define IDC_EDIT_MACHINE_ID             1053
#define IDC_EDIT_MACHINE_REV            1054
#define IDC_EDIT_MACHINE_STATUS         1055
#define IDC_EDIT_MACHINE_T              1056
#define IDC_EDIT_MACHINE_TORQUE         1057
#define IDC_EDIT_CONTRONER_T            1058
#define IDC_EDIT_CONTRONER_V            1059
#define IDC_EDIT_CONTRONER_I            1060
#define IDC_EDIT_L_V_BATTERY_SUBSYS_ID  1061
#define IDC_CUSTOM_T                    1062
#define IDC_CUSTOM1                     1063
#define IDC_LIST1                       1065
#define IDC_BUTTON_ADD                  1066
#define IDC_BUTTON_DEL                  1067
#define IDC_BUTTON_EDIT                 1068
#define IDC_BUTTON_CLEAR                1069
#define IDC_BUTTON_IMPORT               1070
#define IDC_BUTTON_EXPORT               1071
#define IDC_LIST                        1072
#define IDC_EDIT_NAME                   1074
#define IDC_EDIT_ID                     1075
#define IDC_EDIT_START_BYTE             1076
#define IDC_LIST2                       1077
#define IDC_EDIT_START_BITE             1077
#define IDC_EDIT_BITE_LEN               1078
#define IDC_EDIT_RATIO                  1079
#define IDC_EDIT_OFFSET                 1080
#define IDC_EDIT_DESCRIPTION_1          1081
#define IDC_EDIT_DESCRIPTION_2          1082
#define IDC_EDIT_GROUP                  1083
#define IDC_EDIT_FROM                   1085
#define IDC_CHECK_CONST                 1086
#define IDC_EDIT_CONST                  1087
#define IDC_EDIT_CODE                   3001
#define IDC_EDIT_MASK                   3002
#define IDC_COMBO_FILTERTYPE            3003
#define IDC_COMBO_MODE                  3004
#define IDC_EDIT_TIMING0                3005
#define IDC_EDIT_TIMING1                3006
#define ID_MENU_REFRESH                 32771

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        145
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1088
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
